contact/urls.py
from django.urls import path

from contact.views import ContactView

app_name = "contact"
urlpatterns = [
    path("", ContactView.as_view(), name="landing"),
]

core/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.views.generic import TemplateView

from story.sitemap import BlogSiteMap

from . import views
from .sitemap import StaticViewSitemap

sitemaps = {"website": StaticViewSitemap, "blog": BlogSiteMap}

app_name = "core"
urlpatterns = [
    # path(r'^test-404/$', 'core.views.error404'),
    path("events/", views.events, name="events"),
    path("events/map/", views.events_map, name="events_map"),
    path("events/calendar.ics", views.events_ical, name="icalendar"),
    path("resources/", views.resources, name="resources"),
    path("newsletter/", views.newsletter, name="newsletter"),
    path("faq/", views.faq, name="faq"),
    path("foundation/", views.foundation, name="foundation"),
    path("foundation/governing-document/", views.governing_document, name="foundation-governing-document"),
    path("contribute/", views.contribute, name="contribute"),
    path("2015/", views.year_2015, name="year_2015"),
    path("2016-2017/", views.year_2016_2017, name="year_2016_2017"),
    path("terms-conditions/", views.terms_conditions, name="terms-conditions"),
    path("privacy-cookies/", views.privacy_cookies, name="privacy-cookies"),
    # path(r'^workshop-box/$', views.workshop_box, name='workshop-box'),
    path("coc/", views.coc, name="coc"),
    # path(r'^crowdfunding-donors/$', views.crowdfunding_donors, name='crowdfunding-donors'),
    path("server-error/", views.server_error, name="server_error"),
    path("<slug:page_url>/", views.event, name="event"),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="core/txt/robots.txt", content_type="text/plain"),
        name="robots",
    ),
    path("", views.index, name="index"),
    path(
        "google3ef9938c7b93b707.html",
        TemplateView.as_view(template_name="google3ef9938c7b93b707.html"),
        name="google_site_verification",
    ),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
]

djangogirls/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView
from django.views.i18n import JavaScriptCatalog

from core.views import coc_legacy

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    re_path(r"^coc/(?:(?P<lang>[a-z-]+)/)?$", coc_legacy, name="coc_legacy"),
    # Redirection for old CoC's flatpages:
    path("pages/coc/", RedirectView.as_view(url="/coc/", permanent=True)),
    path("pages/coc-es-la/", RedirectView.as_view(url="/coc/es/", permanent=True)),
    path("pages/coc-fr/", RedirectView.as_view(url="/coc/fr/", permanent=True)),
    path("pages/coc-kr/", RedirectView.as_view(url="/coc/ko/", permanent=True)),
    path("pages/coc-pt-br/", RedirectView.as_view(url="/coc/pt-br/", permanent=True)),
    path("pages/coc/rec/", RedirectView.as_view(url="/coc/pt-br/", permanent=True)),
]

urlpatterns += i18n_patterns(
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    # Redirect old links:
    path("pages/in-your-city/", RedirectView.as_view(url="/organize/", permanent=True)),
    path("admin", RedirectView.as_view(url="/admin/", permanent=True)),
    path("admin/core/eventpage/<int>/", RedirectView.as_view(pattern_name="admin:core_event_change")),
    # Admin link for password reset
    # See:
    # https://github.com/darklow/django-suit/blob/92a745d72935622220eca80edfce779419c30094/suit/templates/admin/
    # login.html#L61
    path(
        "admin/password_reset/",
        RedirectView.as_view(url="/account/password_reset", permanent=True),
        name="admin_password_reset",
    ),
    path("tinymce/", include("tinymce.urls")),
    # Regular links:
    path("admin/", admin.site.urls),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("account/", include("django.contrib.auth.urls")),
    path("coach/", include("coach.urls")),
    path("contact/", include("contact.urls")),
    path("donate/", include("donations.urls")),
    path("organize/", include("organize.urls")),
    path("story/", include("story.urls")),
    path("jobs/", include("jobboard.urls")),
    # path('', include('sponsor.urls')),
    path("", include("applications.urls")),
    path("", include("core.urls")),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    try:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls)),
        ] + urlpatterns
    except ImportError:
        pass

donations/urls.py
from django.urls import path

from . import views

app_name = "donations"

urlpatterns = [
    path("", views.index, name="index"),
    path("charge/", views.charge, name="charge"),
    path("success/<str:currency>/<str:amount>/", views.success, name="success"),
    path("error/", views.error, name="error"),
    path("sponsors/", views.sponsors, name="sponsors"),
]

jobboard/urls.py
from django.urls import path

from . import views

app_name = "jobboard"


urlpatterns = [
    path("", views.index, name="index"),
    path("job/<int:id>/", views.job_detail, name="job_detail"),
]

organize/urls.py
from django.urls import path

from . import views

app_name = "organize"
urlpatterns = [
    path("", views.index, name="index"),
    path("prerequisites/", views.prerequisites, name="prerequisites"),
    path("commitment/", views.commitment, name="commitment"),
    path("form/thank_you/", views.form_thank_you, name="form_thank_you"),
    path("form/<slug:step>/", views.organize_form_wizard, name="form_step"),
    # path('remote_or_in_person/', views.remote_or_in_person, name='remote_or_in_person'),
    path("suspend/", views.suspend, name="suspend"),
]

templates/global/base.html
{% load i18n rev static %}

<!DOCTYPE HTML>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
  <title>{% block title %}{% trans "Django Girls - start your journey with programming" %}{% endblock %}</title>
  <meta name="description" content="{% block description %}{% trans "Django Girls is a one-day workshop about programming in Python and Django for women." %}{% endblock %}">
  <meta name="keywords" content="programming, python, django, workshop, women, females">
  <link href="{% static 'img/favicon.ico' %}" rel="shortcut icon">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta property="og:title" content="{% block og_title %}{% trans "Django Girls is a one-day workshop about programming in Python and Django for women" %}{% endblock %}" />
  <meta property="og:type" content="website" />
  <meta property="og:description" content="{% block og_description %}{% trans "Join us and become a female developer! Build your first website in Python and Django in a friendly, safe environment." %}{% endblock %}" />
  <meta property="og:image" content="{% block og_image %}https://raw.githubusercontent.com/olasitarska/djangogirls/gh-pages/resources/graphics/logo_square.png{% endblock %}" />

  <link rel="stylesheet" href="//brick.a.ssl.fastly.net/Lora:400,700,400i,700i/Roboto:300,400,300i,400i">
  {% block main_stylesheet %}<link rel="stylesheet" type="text/css" href="{% static_rev 'css/global.css' %}" media="screen">{% endblock %}
  {% block extra_css %}{% endblock %}

  <script type="text/javascript" src="{% static 'vendor/js/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'vendor/js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'vendor/js/sss.min.js' %}"></script>
  {% block extra_js %}{% endblock %}
</head>
<body>
    <div class="page-wrap">
        {% block menu %}
            {% include 'global/menu.html' %}
        {% endblock %}

        {% block content %}{% endblock %}
    </div>

    {% block footer %}
        {% include 'global/footer.html' %}
    {% endblock %}

    {% include 'includes/js.html' %}
</body>
</html>

templates/global/footer.html
{% load i18n %}

<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <p>Django Girls</p>
                <ul>
                    <li><a href="{% url 'core:faq' %}">{% trans "FAQ" %}</a></li>
                    <li><a href="{% url 'core:foundation' %}">{% trans "Foundation" %}</a></li>
                    <li><a href="{% url 'core:newsletter' %}">{% trans "Newsletter" %}</a></li>
                    <li><a href="http://gitter.im/DjangoGirls/tutorial"><strong>{% trans "Chat with us!" %}</strong></a></li>
                    <li><a href="{% url 'coc_legacy' lang=LANGUAGE_CODE|default:"en" %}">{% trans "Code of Conduct" %}</a></li>
                    <li><a href="{% url 'contact:landing' %}">{% trans "Contact" %}</a></li>
                    <li><a href="{% url 'jobboard:index' %}">{% trans "Job Board" %}</a></li>
                </ul>
            </div>

            <div class="col-md-2">
                <p>{% trans "Support us" %}</p>
                <ul>
                    <li><a href="{% url 'donations:index' %}">{% trans "Make a donation" %}</a></li>
                    <li><a href="https://www.patreon.com/djangogirls">{% trans "Donate on Patreon" %}</a></li>
                    <li><a href="{% url 'core:contribute' %}">{% trans "Contribute" %}</a></li>
                    <li><a href="https://drive.google.com/file/d/1cp774iWVbU5_GcpsUG4Ya9F-RAN8EWiT/view?usp=sharing">{% trans "Sponsor us" %}</a></li>
                    <li><a href="{% url 'donations:sponsors' %}">{% trans "Our Sponsors" %}</a></li>
                </ul>
            </div>
            <div class="col-md-2">
                <p>{% trans "Community" %}</p>
                <ul>
                    <li><a href="http://facebook.com/djangogirls">Facebook</a></li>
                    <li><a href="http://twitter.com/djangogirls">Twitter</a></li>
                    <li><a href="http://github.com/djangogirls">Github</a></li>
                </ul>
            </div>

            <div class="col-md-2">
                <p>{% trans "Resources" %}</p>
                <ul>
                    <li><a href="https://tutorial.djangogirls.org/">{% trans "Tutorial" %}</a></li>
                    <li><a href="https://organize.djangogirls.org/">{% trans "Organizer's Manual" %}</a></li>
                    <li><a href="https://coach.djangogirls.org/">{% trans "Coaching Guide" %}</a></li>
                    <li><a href="https://tutorial-extensions.djangogirls.org/">{% trans "Tutorial Extensions" %}</a></li>
                    <li><a href="https://github.com/DjangoGirls/resources">{% trans "Graphics" %}</a></li>
                </ul>
            </div>

             <div class="col-md-2">
                <p>Website</p>
                <ul>
                    <li><a href="{% url 'core:terms-conditions' %}">{% trans "Terms & Conditions" %}</a></li>
                    <li><a href="{% url 'core:privacy-cookies' %}">{% trans "Privacy & Cookies" %}</a></li>
                </ul>
            </div>

            <div class="col-md-2">
                <p>♥</p>
                <ul>
                    <li>{% blocktrans %}<b>{{ future_events_count }}</b> upcoming events{% endblocktrans %}</li>
                    <li>{% blocktrans %}<b>{{ past_events_count }}</b> past events{% endblocktrans %}</li>
                    <li>{% blocktrans %}<b>{{ applicants_sum }}</b> applicants{% endblocktrans %}</li>
                    <li>{% blocktrans %}<b>{{ attendees_sum }}</b> attendees{% endblocktrans %}</li>
                    <li>{% blocktrans %}<b>{{ countries_count }}</b> countries{% endblocktrans %}</li>
                </ul>
            </div>

        </div>
    </div>
</footer>

templates/global/menu.html
{% load i18n static %}

<div class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="logo">
                <a href="{% url 'core:index' %}">
                    <img src="{% static 'img/global/logo.png' %}" alt="Django Girls" />
                </a>
            </div>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'core:events' %}">{% trans "Events" %}</a></li>
                <li><a href="{% url 'core:resources' %}">{% trans "Resources" %}</a></li>
                <li><a href="{% url 'organize:index' %}">{% trans "Organize" %}</a></li>
                <li><a href="{% url 'core:newsletter' %}">{% trans "Newsletter" %}</a></li>
                <li><a href="https://blog.djangogirls.org/">{% trans "Blog" %}</a></li>
                <li><a href="{% url 'jobboard:index' %}">{% trans "Jobs" %}</a></li>
                <li><a href="{% url 'core:contribute' %}">{% trans "Contribute" %}</a></li>
                
                 <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% trans "Donate to us 💕" %} <span class="caret"></span></a>
                     <ul class="dropdown-menu">
                         <li><a href="{% url 'donations:index' %}">{% trans "Donate" %}</a></li>
                         <li><a href="https://www.patreon.com/djangogirls">{% trans "Our Patreon page" %}</a></li>
                         <li><a href="{% url 'donations:sponsors' %}">{% trans "Our Sponsors" %}</a></li>
                     </ul>
                 </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>